-- H2-compatible schema cho GiaiDau entity
-- Simplified version không có SQL Server-specific syntax

CREATE TABLE IF NOT EXISTS GIAI_DAU (
    ID_GIAI INT AUTO_INCREMENT PRIMARY KEY,
    TEN_GIAI VARCHAR(500),
    NGAY_BD DATE,
    NGAY_KT DATE,
    SO_DOI_THAM_DU INT,
    DIA_DIEM VARCHAR(500),
    TRANG_THAI VARCHAR(50),
    NOI_BAT BOOLEAN DEFAULT FALSE,
    SO_LUOT_XEM INT DEFAULT 0,
    MO_TA_NGAN TEXT,
    MO_TA_DAY_DU TEXT,
    ANH_DAI_DIEN VARCHAR(500),
    ANH_BIA VARCHAR(500),
    VIDEO_GIOI_THIEU VARCHAR(500),
    WEBSITE VARCHAR(500),
    FAN_PAGE VARCHAR(500),
    HOTLINE VARCHAR(20),
    EMAIL VARCHAR(255),
    TINH_THANH VARCHAR(100),
    QUAN_HUYEN VARCHAR(100),
    DIA_CHI_CHI_TIET VARCHAR(500),
    BAN_DO_URL VARCHAR(1000),
    GHI_CHU TEXT,
    NGAY_TAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    NGUOI_TAO VARCHAR(255),
    NGAY_CAP_NHAT TIMESTAMP,
    NGUOI_CAP_NHAT VARCHAR(255)
);
